#!/usr/bin/env node
const{readFileSync}=require("fs"),{join,dirname}=require("path"),https=require("https"),http=require("http"),{createWriteStream}=require("fs"),{execSync}=require("child_process");class VersionManager{constructor(e){this.versionJsonUrls=[e||"https://iot-listrik-dashboard.vercel.app/app-version.json","http://localhost:3000/app-version.json","http://localhost/app-version.json",join(__dirname,"..","app-version.json")],this.versionData=null}async loadVersion(){for(const e of this.versionJsonUrls)try{if(e.startsWith("http")){const t=e.startsWith("https:")?https:http,a=await new Promise((d,l)=>{const o=t.get(e,r=>{let i="";r.on("data",s=>i+=s),r.on("end",()=>{try{d(JSON.parse(i))}catch{l(new Error("Failed to parse version data"))}})});o.on("error",l),o.setTimeout(5e3,()=>{o.destroy(),l(new Error("Request timeout"))})});return this.versionData=a,a}else{const t=JSON.parse(readFileSync(e,"utf8"));return this.versionData=t,t}}catch(t){console.warn(`Failed to load from ${e}: ${t.message}`);continue}throw new Error("Failed to load version data from all sources")}getVersion(){return this.versionData?.version||"unknown"}getDownloadUrl(e,t=null){if(!this.versionData)return null;switch(e.toLowerCase()){case"android":return this.versionData.downloads.android?.url;case"windows":return t==="setup"?this.versionData.downloads.windows?.setup?.url:t==="portable"?this.versionData.downloads.windows?.portable?.url:t==="msi"?this.versionData.downloads.windows?.msi?.url:this.versionData.downloads.windows?.setup?.url;default:return null}}getDownloadFilename(e,t=null){if(!this.versionData)return null;switch(e.toLowerCase()){case"android":return this.versionData.downloads.android?.filename;case"windows":return t==="setup"?this.versionData.downloads.windows?.setup?.filename:t==="portable"?this.versionData.downloads.windows?.portable?.filename:t==="msi"?this.versionData.downloads.windows?.msi?.filename:this.versionData.downloads.windows?.setup?.filename;default:return null}}getAllDownloads(){return this.versionData?.downloads||{}}}async function downloadFile(n,e){return new Promise((t,a)=>{const l=(n.startsWith("https:")?https:http).get(n,o=>{if(o.statusCode!==200){a(new Error(`HTTP ${o.statusCode}: ${o.statusMessage}`));return}const r=parseInt(o.headers["content-length"],10);let i=0;const s=createWriteStream(e);o.pipe(s),o.on("data",c=>{if(i+=c.length,r){const u=(i/r*100).toFixed(1);process.stdout.write(`\rDownloading... ${u}% (${i}/${r} bytes)`)}}),s.on("finish",()=>{s.close(),console.log(`
Download completed!`),t()})});l.on("error",o=>{a(o)}),l.setTimeout(3e4,()=>{l.destroy(),a(new Error("Download timeout"))})})}function detectPlatform(){const n=process.platform,e=process.arch;return n==="win32"?{platform:"windows",arch:e}:n==="android"?{platform:"android",arch:e}:{platform:"unknown",arch:e}}async function main(){const n=process.argv.slice(2);if(n.length===0||n.includes("--help")||n.includes("-h")){console.log(`
IoT Listrik Dashboard - Auto Download CLI
Usage: node download-cli.js [options]

Options:
  --platform <platform>    Platform: windows, android (default: auto-detect)
  --type <type>           Type: setup, portable, msi (Windows only, default: setup)
  --arch <arch>           Architecture: x64, ia32, arm64 (default: auto-detect)
  --output <path>         Output file path (default: auto-generated)
  --latest               Download latest version (default: true)
  --list                 List available downloads
  --help, -h             Show this help

Examples:
  node download-cli.js                    # Download latest for current platform
  node download-cli.js --platform windows --type portable
  node download-cli.js --platform windows --type msi
  node download-cli.js --platform android
  node download-cli.js --list
`);return}if(n.includes("--list")){const o=new VersionManager("https://iot-listrik-dashboard.vercel.app/app-version.json");try{await o.loadVersion(),console.log(`
Latest Version: ${o.getVersion()}`),console.log(`
Available Downloads:`);const r=o.getAllDownloads();Object.entries(r).forEach(([i,s])=>{console.log(`
${i.toUpperCase()}:`),i==="android"?console.log(`  ${s.filename} (${s.size})`):i==="windows"&&(console.log(`  Setup: ${s.setup.filename} (${s.setup.size})`),console.log(`  Portable: ${s.portable.filename} (${s.portable.size})`),s.msi&&console.log(`  MSI: ${s.msi.filename} (${s.msi.size})`))})}catch(r){console.error("Failed to load version information:",r.message),process.exit(1)}return}let e=null,t="setup",a=null,d=null;for(let o=0;o<n.length;o++)switch(n[o]){case"--platform":e=n[++o];break;case"--type":t=n[++o];break;case"--arch":a=n[++o];break;case"--output":d=n[++o];break}if(!e||!a){const o=detectPlatform();e=e||o.platform,a=a||o.arch}console.log(`Detected platform: ${e}, architecture: ${a}`);const l=new VersionManager("https://iot-listrik-dashboard.vercel.app/app-version.json");try{console.log("Loading version information..."),await l.loadVersion(),console.log(`Latest version: ${l.getVersion()}`);const o=l.getDownloadUrl(e,t),r=l.getDownloadFilename(e,t);(!o||!r)&&(console.error(`No download available for platform: ${e}, type: ${t}`),process.exit(1)),d||(d=r),console.log(`Downloading: ${r}`),console.log(`From: ${o}`),console.log(`To: ${d}`);const i=o.startsWith("/")?`http://localhost${o}`:o;await downloadFile(i,d),console.log(`
Success! File saved as: ${d}`),e==="windows"&&t==="setup"&&d.endsWith(".exe")&&(console.log(`
Would you like to run the installer now? (y/N): `),process.stdin.setRawMode(!0),process.stdin.resume(),process.stdin.on("data",s=>{if(s.toString()==="y"||s.toString()==="Y")try{execSync(`"${d}"`,{stdio:"inherit"})}catch{console.log("Installer exited.")}process.exit(0)}))}catch(o){console.error("Error:",o.message),process.exit(1)}}main().catch(console.error);
