#!/usr/bin/env node
const inquirer=require("inquirer"),chalk=require("chalk"),readline=require("readline"),fs=require("fs"),path=require("path"),{initializeApp}=require("firebase/app"),{getAuth,signInWithEmailAndPassword,signOut}=require("firebase/auth"),{getDatabase,ref,onValue,set,get,query,limitToLast,orderByKey,off}=require("firebase/database"),os=require("os"),LEGACY_SESSION_FILE=path.join(os.homedir(),".iot-listrik-session.json"),firebaseConfig={apiKey:"AIzaSyD99N-FQdkTPNnNGY-fof6ijskxg0bzARc",authDomain:"monitoring-listrik-719b1.firebaseapp.com",databaseURL:"https://monitoring-listrik-719b1-default-rtdb.asia-southeast1.firebasedatabase.app",projectId:"monitoring-listrik-719b1",storageBucket:"monitoring-listrik-719b1.firebasestorage.app",messagingSenderId:"115654600721",appId:"1:115654600721:web:6b971ee1c19be7e045a9b0"},app=initializeApp(firebaseConfig),auth=getAuth(app),db=getDatabase(app),DEVICE_STALE_MS=15e3;let pathPrefix="",sessionTimeoutTimer=null,presenceListrikRef=null,presenceConnRef=null,firebaseConnected=!0,lastDeviceHeartbeatAt=0,lastUpdatedMarker=null,lastSensorSignature="",watchStartedAt=Date.now(),latestListrikSnapshot=null,lastAdminResetMarker=null;function isLikelyEpochMs(e){return Number.isFinite(e)&&e>1e12}function buildSensorSignature(e={}){return[Number(e?.arus??0).toFixed(3),Number(e?.tegangan??0).toFixed(1),Number(e?.daya_w??0).toFixed(1),Number(e?.apparent_power??e?.daya??0).toFixed(1),Number(e?.energi_kwh??0).toFixed(4),Number(e?.frekuensi??0).toFixed(2),Number(e?.power_factor??0).toFixed(3),String(e?.status||"NORMAL")].join("|")}function registerDeviceHeartbeat(e){const n=e?.updated_at!=null?Number(e.updated_at):null,a=buildSensorSignature(e);let t=!1;Number.isFinite(n)&&n>0?(lastUpdatedMarker==null?isLikelyEpochMs(n)&&Date.now()-n<=DEVICE_STALE_MS&&(t=!0):n!==lastUpdatedMarker&&(t=!0),lastUpdatedMarker=n):lastSensorSignature&&lastSensorSignature!==a&&(t=!0),lastSensorSignature=a,t&&(lastDeviceHeartbeatAt=Date.now())}function currentConnectionLabel(e=Date.now()){return firebaseConnected?lastDeviceHeartbeatAt?e-lastDeviceHeartbeatAt>DEVICE_STALE_MS?"Device Offline":"Connected":e-watchStartedAt>DEVICE_STALE_MS?"Device Offline":"Memeriksa perangkat...":"Memulihkan..."}function handleAdminResetNotice(e){const n=!!e?.reset_by_admin,a=String(e?.reset_at||"").trim();if(!n||!a)return;if(lastAdminResetMarker==null){lastAdminResetMarker=a;return}if(lastAdminResetMarker===a)return;lastAdminResetMarker=a;const t=String(e?.reset_note||"Admin mengosongkan data realtime sensor perangkat IoT.");console.log(chalk.cyan(`
[INFO] ${t}`))}function relayBlockedReason(){const e=currentConnectionLabel();return e==="Device Offline"?"Perangkat offline. Relay fisik tidak menerima perintah.":e==="Memeriksa perangkat..."?"Sistem masih menunggu heartbeat perangkat.":e==="Memulihkan..."?"Koneksi cloud sedang dipulihkan.":"Perangkat belum siap menerima perintah."}function startPresenceWatch(){presenceListrikRef&&off(presenceListrikRef),presenceConnRef&&off(presenceConnRef),lastDeviceHeartbeatAt=0,lastUpdatedMarker=null,lastSensorSignature="",latestListrikSnapshot=null,lastAdminResetMarker=null,watchStartedAt=Date.now(),presenceListrikRef=ref(db,`${pathPrefix}/listrik`),onValue(presenceListrikRef,e=>{const n=e.val();n&&(latestListrikSnapshot=n,registerDeviceHeartbeat(n),handleAdminResetNotice(n))}),presenceConnRef=ref(db,".info/connected"),onValue(presenceConnRef,e=>{firebaseConnected=!!e.val(),firebaseConnected&&(watchStartedAt=Date.now())})}function stopPresenceWatch(){presenceListrikRef&&(off(presenceListrikRef),presenceListrikRef=null),presenceConnRef&&(off(presenceConnRef),presenceConnRef=null)}function renderLiveMonitoring(e){printHeader(),console.log(chalk.yellow("Memulai Live Stream Data Firebase...")),console.log(chalk.gray(`Tekan 'q' atau 'Ctrl+C' kapan saja untuk kembali ke Menu Utama.
`));const n=currentConnectionLabel(),a=n==="Connected"?chalk.green:n==="Memeriksa perangkat..."?chalk.yellow:chalk.red;if(console.log(chalk.cyan.bold("=== Data Realtime ===")),console.log(`${chalk.blue("Koneksi    :")} ${a(n)}`),!e){console.log(chalk.gray("Belum ada data perangkat."));return}console.log(`${chalk.blue("Waktu      :")} ${e.timestamp||"-"}`),console.log(`${chalk.blue("Arus (A)   :")} ${chalk.white(e.arus||"0")}`),console.log(`${chalk.blue("Tegangan(V):")} ${chalk.white(e.tegangan||"0")}`);const t=Number(e.power_factor??.85),o=Number(e.apparent_power??e.daya??0),s=Number(e.daya_w??o*t);console.log(`${chalk.blue("Daya Aktif :")} ${chalk.white(s.toFixed(1))} W`),console.log(`${chalk.blue("Daya Semu  :")} ${chalk.white(o.toFixed(1))} VA`),console.log(`${chalk.blue("PF / Freq  :")} ${chalk.white(t.toFixed(2))} / ${chalk.white(Number(e.frekuensi??50).toFixed(1))} Hz`);let i=chalk.green;e.status==="WARNING"&&(i=chalk.yellow),e.status==="DANGER"&&(i=chalk.red.bold),console.log(`${chalk.blue("Status     :")} ${i(e.status||"-")}`),console.log(`${chalk.blue("Relay      :")} ${e.relay?chalk.green("ON"):chalk.red("OFF")}`)}function handleSessionExpired(){console.clear(),console.log(chalk.red.bold(`
[!] PERINGATAN SISTEM [!]`)),console.log(chalk.yellow("Durasi sesi akun sementara (Demo) Anda telah habis (15 menit).")),console.log(chalk.gray(`Anda akan di-logout secara otomatis.
`)),fs.existsSync(LEGACY_SESSION_FILE)&&fs.unlinkSync(LEGACY_SESSION_FILE),process.exit(0)}function printHeader(){console.clear(),console.log(chalk.cyan.bold(`
IoT Listrik Dashboard CLI`)),console.log(chalk.gray(`Pengembang: Fatony Ahmad Fauzi
`)),auth.currentUser&&console.log(chalk.green(`[+] Terhubung sebagai: ${auth.currentUser.email}
`))}async function runLiveMonitoring(){return new Promise(e=>{renderLiveMonitoring(latestListrikSnapshot);const n=setInterval(()=>{renderLiveMonitoring(latestListrikSnapshot)},2500),a=(t,o)=>{o&&(o.name==="q"||o.ctrl&&o.name==="c")&&(process.stdin.removeListener("keypress",a),process.stdin.isTTY&&process.stdin.setRawMode(!1),clearInterval(n),e())};readline.emitKeypressEvents(process.stdin),process.stdin.isTTY&&process.stdin.setRawMode(!0),process.stdin.resume(),process.stdin.on("keypress",a)})}async function toggleRelay(){if(currentConnectionLabel()!=="Connected"){console.log(chalk.yellow(`
Perintah relay diblokir: ${relayBlockedReason()}`)),await holdForEnter();return}const{confirmToggle:e}=await inquirer.prompt([{type:"list",name:"confirmToggle",message:"Kontrol Relay Jarak Jauh:",choices:[{name:"Nyalakan Relay (Paksakan ON)",value:!0},{name:"Matikan Relay (Paksakan OFF)",value:!1},{name:"Batal",value:null}]}]);if(e!==null)try{await set(ref(db,`${pathPrefix}/listrik/relay`),e),console.log(chalk.green(`
Berhasil mengirim perintah [${e?"ON":"OFF"}] ke alat!`))}catch(n){console.log(chalk.red(`
Gagal mengirim perintah:`),n.message)}await holdForEnter()}async function viewLogs(){printHeader(),console.log(chalk.cyan(`Memuat 5 log riwayat terakhir...
`));try{const e=query(ref(db,`${pathPrefix}/logs`),orderByKey(),limitToLast(5)),n=await get(e);if(n.exists()){const a=n.val();Object.keys(a).forEach(t=>{const o=a[t],s=new Date(o.timestamp).toLocaleString(),i=o.type==="alert"?chalk.red("[ALERT]"):chalk.green("[INFO]");console.log(`${chalk.gray(s)} ${i} ${o.message}`)})}else console.log(chalk.gray("Belum ada catatan aktivitas."))}catch(e){console.log(chalk.red("Kesalahan saat mengambil data:",e.message))}await holdForEnter()}async function holdForEnter(){await inquirer.prompt([{type:"input",name:"lanjut",message:"Tekan Enter untuk kembali ke Menu Utama...",prefix:""}])}async function enforceLogin(){if(console.clear(),console.log(chalk.cyan.bold(`
IoT Listrik Dashboard CLI`)),console.log(chalk.gray(`Otentikasi Diperlukan
`)),fs.existsSync(LEGACY_SESSION_FILE))try{fs.unlinkSync(LEGACY_SESSION_FILE),console.log(chalk.yellow(`Session lama dihapus karena menyimpan password plaintext. Silakan login manual.
`))}catch{console.log(chalk.red(`Gagal menghapus session lama. Hapus manual file ~/.iot-listrik-session.json.
`))}let e=!1;for(;!e;){const{email:n,password:a}=await inquirer.prompt([{type:"input",name:"email",message:"Email:"},{type:"password",name:"password",message:"Password:"}]);try{await signInWithEmailAndPassword(auth,n,a),await processUserClaims(),startPresenceWatch(),console.log(chalk.green(`
Login berhasil!
`)),e=!0}catch(t){console.log(chalk.red(`
Login gagal:`),t.message,`
`)}}}async function processUserClaims(){const e=await auth.currentUser.getIdTokenResult(!0),n=e.claims.isTempAccount===!0,a=e.claims.expiresAt;if(n){if(pathPrefix=`sim/${auth.currentUser.uid}`,a){const t=a-Date.now();t<=0?handleSessionExpired():(sessionTimeoutTimer&&clearTimeout(sessionTimeoutTimer),sessionTimeoutTimer=setTimeout(handleSessionExpired,t))}}else pathPrefix="",sessionTimeoutTimer&&(clearTimeout(sessionTimeoutTimer),sessionTimeoutTimer=null)}async function handleLogout(){const{logoutConfirm:e}=await inquirer.prompt([{type:"confirm",name:"logoutConfirm",message:"Anda yakin ingin Keluar (Log out)?",default:!1}]);e&&(fs.existsSync(LEGACY_SESSION_FILE)&&fs.unlinkSync(LEGACY_SESSION_FILE),stopPresenceWatch(),await signOut(auth),console.log(chalk.green(`
Berhasil Log out. Aplikasi akan ditutup.`)),process.exit(0))}async function mainMenu(){await enforceLogin();let e=!0;for(;e;){printHeader();const{action:n}=await inquirer.prompt([{type:"list",name:"action",message:"Pilih opsi:",choices:[{name:"[1] Mengakses Live Monitoring",value:"live"},{name:"[2] Catatan Log Terakhir",value:"log"},{name:"[3] Kontrol Relay Power",value:"relay"},{name:"[4] Keluar Sesi (Logout)",value:"logout"},{name:"[0] Matikan Aplikasi (Exit)",value:"exit"}],pageSize:10}]);switch(n){case"live":await runLiveMonitoring();break;case"log":await viewLogs();break;case"relay":await toggleRelay();break;case"logout":await handleLogout();break;case"exit":console.log(chalk.gray(`
Menutup CLI dan menghentikan proses... Sampai jumpa!
`)),stopPresenceWatch(),e=!1,process.exit(0);break}}}mainMenu().catch(e=>{console.error("Kesalahan fatal:",e),process.exit(1)});
