directories:
  output: release
  buildResources: build
appId: com.iotlistrik.dashboard
productName: IoT Listrik Dashboard
files:
  - filter:
      - dist-electron
      - dist
win:
  target:
    - target: nsis
      arch:
        - ia32
        - x64
        - arm64
    - target: portable
      arch:
        - ia32
        - x64
        - arm64
  icon: build/icon.ico
nsis:
  oneClick: false
  perMachine: false
  allowToChangeInstallationDirectory: true
  deleteAppDataOnUninstall: false
electronVersion: 25.9.8
