import{db as m}from"./firebase-config.js";import{initPage as v,populateSidebar as k,initSidebarToggle as E,logout as S,getDbPrefix as g,isTempAccount as w}from"./auth.js";import{createRealtimeChart as R,loadHistoryIntoChart as F}from"./charts.js";import{requestNotificationPermission as T,checkAndNotify as B,checkAdminResetNotify as I,startSystemNotificationFeed as D,initAudio as p,showToast as s,stopWebSiren as O}from"./notifications.js";import{ref as b,query as $,orderByKey as C,limitToLast as G,onValue as f}from"https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js";const c=document.getElementById("historyTbody"),y=document.getElementById("filterStatus"),M=document.getElementById("exportBtn"),N=document.getElementById("logCount"),x=document.getElementById("historyChart");let d=null,i=[],W=null,A=null;function _(){if(A)return;const t=b(m,g()+"/listrik");A=f(t,e=>{const a=e.val();if(!a)return;const o=a.status||"NORMAL",r=Number(a.arus||0),n=Number(a.tegangan||0);B(o,r,n),I(a)})}function h(t){const e=isNaN(Number(t))?new Date(t):new Date(Number(t));return isNaN(e)?t:e.toLocaleString("id-ID",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit",second:"2-digit"})}function Y(t){return t==="LEAKAGE"?"Indikasi arus bocor":t==="DANGER"?"Bahaya - arus abnormal":t==="WARNING"?"Periksa beban":"Sistem stabil"}function u(t){return String(t??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;")}function H(t){const e=String(t||"NORMAL").toUpperCase();return["NORMAL","WARNING","LEAKAGE","DANGER"].includes(e)?e:"UNKNOWN"}function P(t={}){const e=Number(t.arus??0),a=Number(t.tegangan??0),o=Number(t.power_factor??.85),r=Number(t.apparent_power??t.daya??e*a);return{active:Number(t.daya_w??r*o),apparent:r}}function V(t){const e=H(t),a={NORMAL:["#86efac","rgba(22,163,74,.14)"],WARNING:["#fde68a","rgba(245,158,11,.14)"],LEAKAGE:["#fed7aa","rgba(249,115,22,.16)"],DANGER:["#fecaca","rgba(220,38,38,.24)"]},[o,r]=a[e]||["#94a3b8","rgba(148,163,184,.15)"];return`<span style="color:${o};background:${r};padding:3px 10px;border-radius:999px;font-size:11px;font-weight:800;letter-spacing:0.04em;">${u(e)}</span>`}function j(t){if(t.length===0){c.innerHTML='<tr><td colspan="6" style="text-align:center;padding:32px;color:var(--text-secondary);">Belum ada data log</td></tr>',N.textContent="0 log";return}N.textContent=`${t.length} log`,c.innerHTML=t.map(e=>`
    <tr>
      <td data-label="Waktu" class="td-mono text-sm">${u(h(e.waktu))}</td>
      <td data-label="Arus" class="td-mono">${Number(e.arus||0).toFixed(2)} A</td>
      <td data-label="Tegangan" class="td-mono">${Number(e.tegangan||0).toFixed(1)} V</td>
      <td data-label="Status">${V(e.status||"\u2014")}</td>
      <td data-label="Relay" class="td-mono">${e.relay===1?"ON":"OFF"}</td>
      <td data-label="Sumber" class="text-sm text-muted">${u(e.source||"\u2014")}</td>
    </tr>
  `).join("")}function L(){const t=y?.value||"ALL",e=t==="ALL"?i:i.filter(o=>o.status===t);j(e),d&&e.length>0&&F(d,e.slice().reverse().slice(-50));const a=document.querySelector(".table-wrap");a&&a.scrollTo({top:0,behavior:"smooth"})}function K(){const t=$(b(m,g()+"/logs"),C(),G(100));c.innerHTML=`<tr><td colspan="6" style="text-align:center;padding:32px;color:var(--text-secondary);">
    <div style="display:flex;align-items:center;justify-content:center;gap:10px;">
      <div class="spinner"></div> Memuat data log...
    </div></td></tr>`,W=f(t,e=>{i=[],e.forEach(a=>{i.unshift({_key:a.key,...a.val()})}),L()},e=>{s("Gagal memuat log: "+e.message,"error")})}function q(){if(i.length===0){s("Tidak ada data untuk diekspor","warning");return}const t=["Waktu","Arus (A)","Tegangan (V)","Daya Aktif (W)","Daya Semu (VA)","PF","Frekuensi (Hz)","Status","Relay","Sumber"],e=i.map(n=>{const l=P(n);return[h(n.waktu),Number(n.arus||0).toFixed(2),Number(n.tegangan||0).toFixed(1),l.active.toFixed(1),l.apparent.toFixed(1),Number(n.power_factor??0).toFixed(2),Number(n.frekuensi??0).toFixed(1),n.status||"",n.relay===1?"ON":"OFF",n.source||""]}),a=[t,...e].map(n=>n.join(",")).join(`
`),o=new Blob([a],{type:"text/csv"}),r=document.createElement("a");r.href=URL.createObjectURL(o),r.download=`log-listrik-${new Date().toISOString().slice(0,10)}.csv`,r.click(),s("Data berhasil diekspor ke CSV","success")}v({onAuthed:(t,e)=>{k(t,e),E(),x&&(d=R(x)),T(),D({enabled:!w()});try{p()}catch{}window.addEventListener("click",()=>p(),{once:!0}),_(),window.addEventListener("beforeunload",()=>{try{O()}catch{}}),K(),y?.addEventListener("change",L),M?.addEventListener("click",q),document.getElementById("logoutBtn")?.addEventListener("click",S)}});
